#!/usr/bin/python3
# Copyright 2019 Darius Neatu (neatudarius@gmail.com)

import inspect
import pathlib
import os
import sys

current_dir = os.path.dirname(os.path.abspath(
    inspect.getfile(inspect.currentframe())))
root_dir = pathlib.Path(current_dir).parent.parent
sys.path.insert(0, str(root_dir))

from check_utils.grader import Grader


class AstGrader(Grader):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def grade_test(self):
        input, output, ref = self.read()


        # check sum
        try:
            out_sum, ref_sum = int(output[0]), int(ref[0])
        except:
            self.exit(code=-1, err='sum is missing or is not an integer')
        else:
            if out_sum == ref_sum:
                self.add_points(self.max_points)
            else:
                self.exit(
                    code=-1, err='sum - {} vs {}'.format(out_sum, ref_sum))

       

if __name__ == '__main__':
    assert len(sys.argv) == 5, sys.argv
    AstGrader(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]).run()
